services:
  # Ini adalah Web Service untuk menjalankan Laravel
  - type: web
    name: cafe-wening # Anda bisa ganti nama ini
    env: php
    plan: free
    region: singapore # Lokasi server terdekat
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

  # Ini adalah Database PostgreSQL gratis
  - type: pserv
    name: cafe-wening-db
    env: postgres
    plan: free
    region: singapore
    disk:
      name: postgres-data
      sizeGB: 1