# render.yaml - Versi Final yang Sudah Benar

services:
  - type: web
    name: cafe-wening
    env: php
    plan: free
    region: singapore
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

databases:
  - name: cafe-wening-db
    plan: free